### ISSUE TITLE
Saving Weights

### ISSUE THREAD

**Issue by MinuteswithMetrics** [jimmy15923/Miccai_challenge_MONUSEG#1]
How can I update the code to save all weights versus saving over each weight? 

For example mask_rcnn_0001.h5

**Comment by jimmy15923** [comment]
Please modify the function  **set_log_dir** in model.py. The original version by Matterport is saving all weights over each epoch, https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/model.py.
