### ISSUE TITLE
some problems in evaluation

### ISSUE THREAD

**Issue by li-pengcheng** [jimmy15923/Miccai_challenge_MONUSEG#2]
I'm a novice in python and keras,when i run your code, i met some problems when evaluation:
here are what i do:
1 first changed the 25 lines of monuconfig.py: NAME="COCO"
2 then modified train.py: 
# Create model
model = modellib. MaskRCNN (mode = "training", config = config, Model_dir = args. Logs, is_PANet = False)
3.run python train.py --weight imagenet --dataset dataset/ --logs logs/ --subset train
here are the mistakes:
USING RESNET
USING PATH AGGREGATION NETWORK, YOU CAN CHANGE MODEL IN TRAIN.PY WHEN CREATING modellib.MaskRCNN
LOADING WEIGHTS FROM logs/COCO_2018-10-16_20-30-39\mask_rcnn_coco_2018-10-16_20-30-39.h5
EVALUATING...
Reading data array & mask array from disk
Traceback (most recent call last):
  File "D:/Projects/Pycharm/MoNuSeg/train.py", line 408, in <module>
    ajx_result = evaluate(model_infer, args.dataset, trained_weights_path, infer_config)
  File "D:/Projects/Pycharm/MoNuSeg/train.py", line 306, in evaluate
    model.load_weights(model_path, by_name=True)
  File "D:\Projects\Pycharm\MoNuSeg\mrcnn\model.py", line 2674, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, layers)
  File "D:\Projects\Anaconda3\envs\tf3\lib\site-packages\keras\engine\saving.py", line 1017, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #377 (named "mrcnn_class_conv1"), weight <tf.Variable 'mrcnn_class_conv1_1/kernel:0' shape=(3, 3, 256, 256) dtype=float32_ref> has shape (3, 3, 256, 256), but the saved weight has shape (1024, 256, 7, 7).

Can you tell me in detail how to modify the parameters to run this code?

**Comment by jimmy15923** [comment]
Hi! Make sure your training and evaluating are used the same model. It looks like you train your model by Mask R-CNN but evaluated in PANet.

**Comment by li-pengcheng** [comment]
So I should revise 
model_infer= modellib.MaskRCNN(mode="inference", config=infer_config,
                                  model_dir=args.logs)
as
model_infer= modellib.MaskRCNN(mode="inference", config=infer_config,
                                  model_dir=args.logs, is_PANet=False)
if i use Mask R-CNN？

**Comment by jimmy15923** [comment]
Yes! I may update the code if I have time since I think build model by this code will be more intuitive!
```
modellib.PANet(...)
```

**Comment by li-pengcheng** [comment]
another question, what should i do if i just want to evaluate my trained model? I found that the code will automatically  combining time and model name, how should I specify a fixed model to evaluate？

**Comment by jimmy15923** [comment]
Please follow the code in inspect_result/inspect_model_result.ipynb
